---
version: 2
sources:
- name: "qa_team_qa_orchestration"
  database: "qa_team"
  schema: "qa_orchestration"
  tables:
  - name: "table_data_records"
    config:
      tags:
      - "pipeline:sample_test_pipeline"
    columns:
    - name: "department"
      dataType:
        type: "String"
    - name: "id"
      dataType:
        type: "Double"
    - name: "name"
      dataType:
        type: "String"
    - name: "role"
      dataType:
        type: "String"
    - name: "salary"
      dataType:
        type: "Double"
    - name: "status"
      dataType:
        type: "String"
    type: "table"
